In [6]:
import numpy as np

arr = np.array([2,3,4,5])
print(arr)
print(type(arr))
print(np.ndim(arr)) #ndim = number of dimensions
#ndarray = n-dimensional array

[2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
arr = np.array([[2,3],[4,5]])
print(arr)
print(np.ndim(arr)) #ndim = number of dimensions

[[2 3]
 [4 5]]
2


In [9]:
arr = np.array(["3",4,5,True,6.8, "hello"])
print(arr)

['3' '4' '5' 'True' '6.8']


In [11]:
arr = np.array([[[20,30],[40,50]],[[60,70],[80,90]]])
print(arr)
print(np.ndim(arr))

[[[20 30]
  [40 50]]

 [[60 70]
  [80 90]]]
3
