In [9]:
import numpy as np

a = np.array([20,30,40])
b = np.array([4])
print(a)
print(b)
print(a*b)


[20 30 40]
[4]
[ 80 120 160]


In [17]:
a = np.array([[20,30,10],[40,50,60]])
print(a)

[[20 30 10]
 [40 50 60]]


In [15]:
l1 = [[20,30],[40,50,60]]
print(l1)

[[20, 30], [40, 50, 60]]
