In [1]:
a = [30,40,50]
b = [5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [10]:
#Concatenate
import numpy as np
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [15]:
print(np.concatenate([arr1,arr2],axis = 1))

[[30 40  5  5]
 [50 10  3  3]]


In [14]:
print(np.hstack([arr1,arr2])) #horizontal concatenation

[[30 40  5  5]
 [50 10  3  3]]


In [16]:
print(np.vstack([arr1,arr2])) #vertical concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [25]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,2)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]])]
